### PR TITLE
Add pagination support

### LINKED ISSUE #6: Pagable who replied list
When a high number of unique members replying to a thread, the "Who replied" page takes longer and longer to load.

It would be desirable to cap this to a per-page amount, and then page through the list in the current ordering.

Ideally this will use AJAX to load the next page into the overlay if possible.

### PR DESCRIPTION
**Pull request by jrahmy**
Closes #6

### CODE REVIEW

**Comment by Fuhrmann** [comment]
Hey! This is great. Thanks for supporting this project. I have merged your pull request and will release a new version.

**Comment by Xon** [comment]
@Fuhrmann fyi this references an external javascript file. XenForo will fail to load the overlay it the required javascript files don't exist.

And CSS is a bit squirrely.

**Comment by Fuhrmann** [comment]
@Xon Thanks!

@jrahmy can you take a look at this?

**Comment by jrahmy** [comment]
Will pull in @Xon's changes and push further fixes shortly.

**Pull request merged**
