### PR TITLE
Fix pagination support

### PR DESCRIPTION
**Pull request by jrahmy**
Addresses previous issues and moves JS into standalone file. The correct triggers are now added to dynamically inserted page links. There may be room for improvement, but per https://github.com/jrahmy/xenforo-who-replied/commit/6a6c0b61c026530f6e2fcb0215cc290e7e53eb30#commitcomment-19621212 I had trouble calling xfActivate() on the individual elements.

### CODE REVIEW

**Comment by Fuhrmann** [comment]
Since I am not anymore developing to XenForo, I'll let this for you to decide whether this pull request needs improvements or it's ok as it is @Xon. Btw, thanks for the pull request @jrahmy.

**Comment by Xon** [comment]
@Fuhrmann Would you be kind enough to release this? It isn't the best solution but it will do for now. XF2 will probably require a completely different way todo this.

**Comment by Xon** [comment]
God damn browsers;
```
SCRIPT5007: Unable to get property 'getItemWrap' of undefined or null reference
eval code (5) (1,175)
```

**Comment by jrahmy** [comment]
Drat. Browser/OS version? I'll take a look tomorrow.

Also GC seems to take care of any memory overhead, so I'm not sure if the penalty is all that great:
image

**Comment by Xon** [comment]
IE10, Windows 10 w/ Anniversary update.

Except it isn't occurring now? What the heck. Perhaps installing/template issues?

**Comment by Xon** [comment]
@jrahmy someone else is reporting this occurring with what looks like Chrome; https://xenforo.com/community/threads/who-replied.46305/page-5#post-1109330

**Comment by Fuhrmann** [comment]
@Xon I just saw your message and you already released. Do you want me to upload to XenForo?

**Comment by jrahmy** [comment]
Let's track down this issue first. Having trouble reproducing, but I'm looking into it.

**Comment by Fuhrmann** [comment]
Nice, thanks @jrahmy .

**Comment by jrahmy** [comment]
@Xon I've had no luck reproducing locally on Chrome, FF, IE, or Edge :unamused:

Without being able to reproduce consistently, the only thing I can think of is some sort of race-condition where ```this.api``` doesn't exist when the conditional is evaluated. I can try to defer it with setTimeout(), but that's all I can really think of.

**Comment by maitikeisi** [comment]
Hi, I'm the guy known as TMC at xenforo forums. If needed I could give access to my beta/testing site that can be tested to see the issue. It seems to almost happen with the same threads, but really no idea what causes it. At first I thought it was happening on all threads with lots of replies, but that doesn't seem to be the case either.

Did a quick gif of the problem, you can't see the mouse cursor but I went over those one by one and only few worked:

jejeje

**Comment by jrahmy** [comment]
@maitikeisi I would really appreciate it, I can't seem to reproduce no matter what I try. If it's a race condition, the following contains a potential fix (the raw file can be uploaded, overriding the existing js/whoreplied/whoreplied.js): https://gist.github.com/jrahmy/0d61ae98acd894fab56aec30562803ab

Feel free to PM me on XF: [https://xenforo.com/community/conversations/add?to=Jeremy P](https://xenforo.com/community/conversations/add?to=Jeremy P)

**Comment by maitikeisi** [comment]
@jrahmy That new version seems to work much better. Worked fine on chrome and edge, but firefox gave an error:
GET 
XHR 
http://beta.REMOVED.fi/js/whoreplied/whoreplied.js [HTTP/1.1 200 OK 0ms]
ExtLoader Failure parsererror 200

Gif taken on chrome:
chrome

I will get back to you later about the dev site if needed, heading to school now.

**Comment by jrahmy** [comment]
Glad to hear it seems to be working! Thanks for your help in testing.

I had the same issue earlier on FireFox. It appears something between FireFox and ExtLoader doesn't like the strict mode string, so I removed it and it seemed to work fine. You may want to try clearing your cache, as the new version should have fixed that as well.

**Comment by maitikeisi** [comment]
Yes, you are right looks like it was just a caching issue with firefox. Did the previous test with ctrl+f5 refresh, but for some reason it didn't clear the cache anyhow. Downloaded portable firefox and worked just fine, so everything looks a-okay now...

**Comment by jrahmy** [comment]
Alternative fix, was finally able to consistently reproduce. It was something much simpler (and dumber, on my part) than I thought. If you would try replacing your JS to test one last time, I would greatly appreciate it: https://raw.githubusercontent.com/jrahmy/xenforo-who-replied/master/upload/js/whoreplied/whoreplied.js

My apologies for all the trouble.

**Comment by maitikeisi** [comment]
Seemed to work fine on all three browsers that I tested (FF, Edge, Chrome). Even added cache buster string for the .js to the whoreplied_list template to make sure that none of them loaded it from cache.

And no problem, happy to help out a bit!

**Pull request merged**
